language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database migratetest;' -U postgres
  - mysql -e 'create database migratetest;'

script: go test -p 1 ./...
